{
  imports = [
    ./conform.nix
    ./cmp.nix
    ./codeium.nix
    ./colorschemes.nix
    ./comment-nvim.nix
    ./conform.nix
    ./extra
    ./fidget.nix
    ./gitsigns.nix
    ./harpoon.nix
    ./inc-rename.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./luasnip.nix
    ./neogen.nix
    ./neotree.nix
    ./nvim-cmp.nix
    ./surround.nix
    ./telescope.nix
    ./tmux-navigator.nix
    ./treesitter-context.nix
    ./treesitter-textobjects.nix
    ./treesitter.nix
    ./trouble.nix
    ./ts-autotag.nix
    ./ts-context-commentstring.nix
    ./undotree.nix
    ./which-key.nix
    ./yanky.nix
  ];
}
